### ISSUE TITLE
[Bug] CHD decoding error

### ISSUE THREAD

**Issue by Immersion95** [Senryoku/Deecy#134]
The game won't start, I have this message : error(ui): Error: InvalidMapCRC

**Comment by Senryoku** [comment]
Please include more information about the exact dump exhibiting the issue (Complete filename, region, hash,... Anything that'll help me find it). All the copies I found worked fine.

Edit: Found it. Looking into it!

**Comment by Senryoku** [comment]
15350e7b02f312c6c58759ca539bbd885302b62c should fix it.

**Comment by Immersion95** [comment]
Yes it solved Ikaruga but now I encounter this error in other games with build 9700bdc9dd9a0423720e7fd8143d7ef4873f0563

- Bakumatsu Roman Daini Maku - Gekka no Kenshi - Final Edition (Japan)
- King of Fighters, The - Dream Match 1999 (Japan) (En,Ja,Es,Pt)
- Street Fighter Zero 3 - Saikyo-ryu Dojo for Matching Service (Japan)

**Comment by Senryoku** [comment]
Which dumps are you using? I can't reproduce it with redump versions.

**Comment by Immersion95** [comment]
Yes I only use Redump. I also tried with the build with https://github.com/Senryoku/Deecy/commit/5f116c2be71530c797a41528f7014e2420ceaf80

I will try to recompress it with latest chdman.

**Comment by Immersion95** [comment]
I tested the gdi Redump version of "Street Fighter Zero 3 - Saikyo-ryu Dojo for Matching Service (Japan)" and it still doesn't launch with this error : 

- error(ui): Failed to load disc: InvalidCharacter

It may be a problem with the special characters of the files.

**Comment by Senryoku** [comment]
Still have no issue with the CHD versions.
For the GDI, I guess the track filenames have spaces and are quoted in the .gdi file? f7e88079537ddbe1e0b15fe94d24dc1ba1154845 should fix that.

**Comment by Immersion95** [comment]
The 3 games now launch but only SFZ3 works correctly.

For Last Blade & KOF Dream match - I have the message regarding the AV Cable not being supported.

**Comment by Senryoku** [comment]
Is the video cable forced to `VGA`? Works fine for me with any other cable setting.
Not that resetting is not enough after after changing to `Auto`, you have to relaunch the game from the menu for the VGA support check to run.

**Comment by Immersion95** [comment]
I'm using Auto Region + Auto Cable. Latest https://github.com/Senryoku/Deecy/commit/416d283727b879e7c52403c64729a1d36db96915

**Comment by Senryoku** [comment]
Mmh, I'm a bit confused why I can't reproduce it, I guess I don't have have the exact same dumps.
I am closing this since the original issue if fixed, but feel free to open a new one with the full list of dumps exhibiting the issue.

**Comment by Senryoku** [comment]
> The 3 games now launch but only SFZ3 works correctly.
> 
> For Last Blade & KOF Dream match - I have the message regarding the AV Cable not being supported.

Ah, this was only an issue when launching a game from the CLI, 9831169 should fix it.

**Comment by Immersion95** [comment]
Yes I only use it with CLI :)
